version: "2"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  enable:
    - errorlint
    - gocritic
    - gomodguard
    - misspell
    - perfsprint
    - testifylint
    - thelper
    - unparam
    - usestdlibvars
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - appendAssign
        - assignOp # Keep it disabled for readability
        - badCond
        - commentFormatting
        - exitAfterDefer
        - ifElseChain
        - mapKey
        - singleCaseSwitch
        - typeSwitchVar
    gomodguard:
      blocked:
        modules:
          - github.com/pkg/errors:
              recommendations:
                - errors
    perfsprint:
      # Optimizes even if it requires an int or uint type cast.
      int-conversion: true
      # Optimizes into `err.Error()` even if it is only equivalent for non-nil errors.
      err-error: true
      # Optimizes `fmt.Errorf`.
      errorf: false
      # Optimizes `fmt.Sprintf` with only one argument.
      sprintf1: true
      # Optimizes into strings concatenation.
      strconcat: true
    testifylint:
      enable-all: true
      disable:
        - go-require
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - unparam
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/kubecano/cano-collector
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
