// Code generated by MockGen. DO NOT EDIT.
// Source: destination.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	issue "github.com/kubecano/cano-collector/pkg/core/issue"
)

// MockDestinationInterface is a mock of DestinationInterface interface.
type MockDestinationInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDestinationInterfaceMockRecorder
}

// MockDestinationInterfaceMockRecorder is the mock recorder for MockDestinationInterface.
type MockDestinationInterfaceMockRecorder struct {
	mock *MockDestinationInterface
}

// NewMockDestinationInterface creates a new mock instance.
func NewMockDestinationInterface(ctrl *gomock.Controller) *MockDestinationInterface {
	mock := &MockDestinationInterface{ctrl: ctrl}
	mock.recorder = &MockDestinationInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDestinationInterface) EXPECT() *MockDestinationInterfaceMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockDestinationInterface) Send(ctx context.Context, issue *issue.Issue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, issue)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockDestinationInterfaceMockRecorder) Send(ctx, issue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockDestinationInterface)(nil).Send), ctx, issue)
}
