// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kubecano/cano-collector/pkg/interfaces (interfaces: DestinationInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDestinationInterface is a mock of DestinationInterface interface.
type MockDestinationInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDestinationInterfaceMockRecorder
}

// MockDestinationInterfaceMockRecorder is the mock recorder for MockDestinationInterface.
type MockDestinationInterfaceMockRecorder struct {
	mock *MockDestinationInterface
}

// NewMockDestinationInterface creates a new mock instance.
func NewMockDestinationInterface(ctrl *gomock.Controller) *MockDestinationInterface {
	mock := &MockDestinationInterface{ctrl: ctrl}
	mock.recorder = &MockDestinationInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDestinationInterface) EXPECT() *MockDestinationInterfaceMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockDestinationInterface) Send(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockDestinationInterfaceMockRecorder) Send(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockDestinationInterface)(nil).Send), arg0, arg1)
}
