// Code generated by MockGen. DO NOT EDIT.
// Source: registry.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	config_destination "github.com/kubecano/cano-collector/config/destination"
	interfaces "github.com/kubecano/cano-collector/pkg/destination/interfaces"
)

// MockDestinationRegistryInterface is a mock of DestinationRegistryInterface interface.
type MockDestinationRegistryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDestinationRegistryInterfaceMockRecorder
}

// MockDestinationRegistryInterfaceMockRecorder is the mock recorder for MockDestinationRegistryInterface.
type MockDestinationRegistryInterfaceMockRecorder struct {
	mock *MockDestinationRegistryInterface
}

// NewMockDestinationRegistryInterface creates a new mock instance.
func NewMockDestinationRegistryInterface(ctrl *gomock.Controller) *MockDestinationRegistryInterface {
	mock := &MockDestinationRegistryInterface{ctrl: ctrl}
	mock.recorder = &MockDestinationRegistryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDestinationRegistryInterface) EXPECT() *MockDestinationRegistryInterfaceMockRecorder {
	return m.recorder
}

// GetDestination mocks base method.
func (m *MockDestinationRegistryInterface) GetDestination(name string) (interfaces.DestinationInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDestination", name)
	ret0, _ := ret[0].(interfaces.DestinationInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDestination indicates an expected call of GetDestination.
func (mr *MockDestinationRegistryInterfaceMockRecorder) GetDestination(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDestination", reflect.TypeOf((*MockDestinationRegistryInterface)(nil).GetDestination), name)
}

// GetDestinations mocks base method.
func (m *MockDestinationRegistryInterface) GetDestinations(names []string) ([]interfaces.DestinationInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDestinations", names)
	ret0, _ := ret[0].([]interfaces.DestinationInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDestinations indicates an expected call of GetDestinations.
func (mr *MockDestinationRegistryInterfaceMockRecorder) GetDestinations(names interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDestinations", reflect.TypeOf((*MockDestinationRegistryInterface)(nil).GetDestinations), names)
}

// LoadFromConfig mocks base method.
func (m *MockDestinationRegistryInterface) LoadFromConfig(config config_destination.DestinationsConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadFromConfig", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadFromConfig indicates an expected call of LoadFromConfig.
func (mr *MockDestinationRegistryInterfaceMockRecorder) LoadFromConfig(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadFromConfig", reflect.TypeOf((*MockDestinationRegistryInterface)(nil).LoadFromConfig), config)
}

// RegisterDestination mocks base method.
func (m *MockDestinationRegistryInterface) RegisterDestination(name string, destination interfaces.DestinationInterface) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterDestination", name, destination)
}

// RegisterDestination indicates an expected call of RegisterDestination.
func (mr *MockDestinationRegistryInterfaceMockRecorder) RegisterDestination(name, destination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterDestination", reflect.TypeOf((*MockDestinationRegistryInterface)(nil).RegisterDestination), name, destination)
}
