// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kubecano/cano-collector/config (interfaces: FullConfigLoader)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	destination "github.com/kubecano/cano-collector/config/config_destination"
	team "github.com/kubecano/cano-collector/config/team"
)

// MockFullConfigLoader is a mock of FullConfigLoader interface.
type MockFullConfigLoader struct {
	ctrl     *gomock.Controller
	recorder *MockFullConfigLoaderMockRecorder
}

// MockFullConfigLoaderMockRecorder is the mock recorder for MockFullConfigLoader.
type MockFullConfigLoaderMockRecorder struct {
	mock *MockFullConfigLoader
}

// NewMockFullConfigLoader creates a new mock instance.
func NewMockFullConfigLoader(ctrl *gomock.Controller) *MockFullConfigLoader {
	mock := &MockFullConfigLoader{ctrl: ctrl}
	mock.recorder = &MockFullConfigLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFullConfigLoader) EXPECT() *MockFullConfigLoaderMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockFullConfigLoader) Load() (destination.DestinationsConfig, team.TeamsConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(destination.DestinationsConfig)
	ret1, _ := ret[1].(team.TeamsConfig)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Load indicates an expected call of Load.
func (mr *MockFullConfigLoaderMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockFullConfigLoader)(nil).Load))
}
