// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kubecano/cano-collector/pkg/interfaces (interfaces: MetricsInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockMetricsInterface is a mock of MetricsInterface interface.
type MockMetricsInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsInterfaceMockRecorder
}

// MockMetricsInterfaceMockRecorder is the mock recorder for MockMetricsInterface.
type MockMetricsInterfaceMockRecorder struct {
	mock *MockMetricsInterface
}

// NewMockMetricsInterface creates a new mock instance.
func NewMockMetricsInterface(ctrl *gomock.Controller) *MockMetricsInterface {
	mock := &MockMetricsInterface{ctrl: ctrl}
	mock.recorder = &MockMetricsInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsInterface) EXPECT() *MockMetricsInterfaceMockRecorder {
	return m.recorder
}

// ClearMetrics mocks base method.
func (m *MockMetricsInterface) ClearMetrics() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearMetrics")
}

// ClearMetrics indicates an expected call of ClearMetrics.
func (mr *MockMetricsInterfaceMockRecorder) ClearMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearMetrics", reflect.TypeOf((*MockMetricsInterface)(nil).ClearMetrics))
}

// IncAlertErrors mocks base method.
func (m *MockMetricsInterface) IncAlertErrors(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncAlertErrors", arg0, arg1)
}

// IncAlertErrors indicates an expected call of IncAlertErrors.
func (mr *MockMetricsInterfaceMockRecorder) IncAlertErrors(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncAlertErrors", reflect.TypeOf((*MockMetricsInterface)(nil).IncAlertErrors), arg0, arg1)
}

// IncAlertsProcessed mocks base method.
func (m *MockMetricsInterface) IncAlertsProcessed(arg0, arg1, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncAlertsProcessed", arg0, arg1, arg2)
}

// IncAlertsProcessed indicates an expected call of IncAlertsProcessed.
func (mr *MockMetricsInterfaceMockRecorder) IncAlertsProcessed(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncAlertsProcessed", reflect.TypeOf((*MockMetricsInterface)(nil).IncAlertsProcessed), arg0, arg1, arg2)
}

// IncDestinationErrors mocks base method.
func (m *MockMetricsInterface) IncDestinationErrors(arg0, arg1, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncDestinationErrors", arg0, arg1, arg2)
}

// IncDestinationErrors indicates an expected call of IncDestinationErrors.
func (mr *MockMetricsInterfaceMockRecorder) IncDestinationErrors(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncDestinationErrors", reflect.TypeOf((*MockMetricsInterface)(nil).IncDestinationErrors), arg0, arg1, arg2)
}

// IncDestinationMessagesSent mocks base method.
func (m *MockMetricsInterface) IncDestinationMessagesSent(arg0, arg1, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncDestinationMessagesSent", arg0, arg1, arg2)
}

// IncDestinationMessagesSent indicates an expected call of IncDestinationMessagesSent.
func (mr *MockMetricsInterfaceMockRecorder) IncDestinationMessagesSent(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncDestinationMessagesSent", reflect.TypeOf((*MockMetricsInterface)(nil).IncDestinationMessagesSent), arg0, arg1, arg2)
}

// IncRoutingDecisions mocks base method.
func (m *MockMetricsInterface) IncRoutingDecisions(arg0, arg1, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncRoutingDecisions", arg0, arg1, arg2)
}

// IncRoutingDecisions indicates an expected call of IncRoutingDecisions.
func (mr *MockMetricsInterfaceMockRecorder) IncRoutingDecisions(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncRoutingDecisions", reflect.TypeOf((*MockMetricsInterface)(nil).IncRoutingDecisions), arg0, arg1, arg2)
}

// IncTeamsMatched mocks base method.
func (m *MockMetricsInterface) IncTeamsMatched(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncTeamsMatched", arg0, arg1)
}

// IncTeamsMatched indicates an expected call of IncTeamsMatched.
func (mr *MockMetricsInterfaceMockRecorder) IncTeamsMatched(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncTeamsMatched", reflect.TypeOf((*MockMetricsInterface)(nil).IncTeamsMatched), arg0, arg1)
}

// ObserveAlert mocks base method.
func (m *MockMetricsInterface) ObserveAlert(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveAlert", arg0, arg1)
}

// ObserveAlert indicates an expected call of ObserveAlert.
func (mr *MockMetricsInterfaceMockRecorder) ObserveAlert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveAlert", reflect.TypeOf((*MockMetricsInterface)(nil).ObserveAlert), arg0, arg1)
}

// ObserveAlertProcessingDuration mocks base method.
func (m *MockMetricsInterface) ObserveAlertProcessingDuration(arg0 string, arg1 int, arg2 time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveAlertProcessingDuration", arg0, arg1, arg2)
}

// ObserveAlertProcessingDuration indicates an expected call of ObserveAlertProcessingDuration.
func (mr *MockMetricsInterfaceMockRecorder) ObserveAlertProcessingDuration(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveAlertProcessingDuration", reflect.TypeOf((*MockMetricsInterface)(nil).ObserveAlertProcessingDuration), arg0, arg1, arg2)
}

// ObserveDestinationSendDuration mocks base method.
func (m *MockMetricsInterface) ObserveDestinationSendDuration(arg0, arg1 string, arg2 time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveDestinationSendDuration", arg0, arg1, arg2)
}

// ObserveDestinationSendDuration indicates an expected call of ObserveDestinationSendDuration.
func (mr *MockMetricsInterfaceMockRecorder) ObserveDestinationSendDuration(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveDestinationSendDuration", reflect.TypeOf((*MockMetricsInterface)(nil).ObserveDestinationSendDuration), arg0, arg1, arg2)
}

// ObserveHTTPRequestDuration mocks base method.
func (m *MockMetricsInterface) ObserveHTTPRequestDuration(arg0, arg1, arg2 string, arg3 time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveHTTPRequestDuration", arg0, arg1, arg2, arg3)
}

// ObserveHTTPRequestDuration indicates an expected call of ObserveHTTPRequestDuration.
func (mr *MockMetricsInterfaceMockRecorder) ObserveHTTPRequestDuration(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveHTTPRequestDuration", reflect.TypeOf((*MockMetricsInterface)(nil).ObserveHTTPRequestDuration), arg0, arg1, arg2, arg3)
}

// PrometheusMiddleware mocks base method.
func (m *MockMetricsInterface) PrometheusMiddleware() gin.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrometheusMiddleware")
	ret0, _ := ret[0].(gin.HandlerFunc)
	return ret0
}

// PrometheusMiddleware indicates an expected call of PrometheusMiddleware.
func (mr *MockMetricsInterfaceMockRecorder) PrometheusMiddleware() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrometheusMiddleware", reflect.TypeOf((*MockMetricsInterface)(nil).PrometheusMiddleware))
}
