// Code generated by MockGen. DO NOT EDIT.
// Source: slack_thread_manager.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSlackThreadManagerInterface is a mock of SlackThreadManagerInterface interface.
type MockSlackThreadManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSlackThreadManagerInterfaceMockRecorder
}

// MockSlackThreadManagerInterfaceMockRecorder is the mock recorder for MockSlackThreadManagerInterface.
type MockSlackThreadManagerInterfaceMockRecorder struct {
	mock *MockSlackThreadManagerInterface
}

// NewMockSlackThreadManagerInterface creates a new mock instance.
func NewMockSlackThreadManagerInterface(ctrl *gomock.Controller) *MockSlackThreadManagerInterface {
	mock := &MockSlackThreadManagerInterface{ctrl: ctrl}
	mock.recorder = &MockSlackThreadManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlackThreadManagerInterface) EXPECT() *MockSlackThreadManagerInterfaceMockRecorder {
	return m.recorder
}

// Cleanup mocks base method.
func (m *MockSlackThreadManagerInterface) Cleanup() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cleanup")
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockSlackThreadManagerInterfaceMockRecorder) Cleanup() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockSlackThreadManagerInterface)(nil).Cleanup))
}

// GetThreadTS mocks base method.
func (m *MockSlackThreadManagerInterface) GetThreadTS(ctx context.Context, fingerprint string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThreadTS", ctx, fingerprint)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThreadTS indicates an expected call of GetThreadTS.
func (mr *MockSlackThreadManagerInterfaceMockRecorder) GetThreadTS(ctx, fingerprint interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThreadTS", reflect.TypeOf((*MockSlackThreadManagerInterface)(nil).GetThreadTS), ctx, fingerprint)
}

// InvalidateThread mocks base method.
func (m *MockSlackThreadManagerInterface) InvalidateThread(fingerprint string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidateThread", fingerprint)
}

// InvalidateThread indicates an expected call of InvalidateThread.
func (mr *MockSlackThreadManagerInterfaceMockRecorder) InvalidateThread(fingerprint interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateThread", reflect.TypeOf((*MockSlackThreadManagerInterface)(nil).InvalidateThread), fingerprint)
}

// SetThreadTS mocks base method.
func (m *MockSlackThreadManagerInterface) SetThreadTS(fingerprint, threadTS string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetThreadTS", fingerprint, threadTS)
}

// SetThreadTS indicates an expected call of SetThreadTS.
func (mr *MockSlackThreadManagerInterfaceMockRecorder) SetThreadTS(fingerprint, threadTS interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetThreadTS", reflect.TypeOf((*MockSlackThreadManagerInterface)(nil).SetThreadTS), fingerprint, threadTS)
}
