// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kubecano/cano-collector/config (interfaces: TeamsLoader)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	config "github.com/kubecano/cano-collector/config"
)

// MockTeamsLoader is a mock of TeamsLoader interface.
type MockTeamsLoader struct {
	ctrl     *gomock.Controller
	recorder *MockTeamsLoaderMockRecorder
}

// MockTeamsLoaderMockRecorder is the mock recorder for MockTeamsLoader.
type MockTeamsLoaderMockRecorder struct {
	mock *MockTeamsLoader
}

// NewMockTeamsLoader creates a new mock instance.
func NewMockTeamsLoader(ctrl *gomock.Controller) *MockTeamsLoader {
	mock := &MockTeamsLoader{ctrl: ctrl}
	mock.recorder = &MockTeamsLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamsLoader) EXPECT() *MockTeamsLoaderMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockTeamsLoader) Load() (*config.TeamsConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(*config.TeamsConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockTeamsLoaderMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockTeamsLoader)(nil).Load))
}
