// Code generated by MockGen. DO NOT EDIT.
// Source: workflow_engine.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	workflow "github.com/kubecano/cano-collector/config/workflow"
	event "github.com/kubecano/cano-collector/pkg/core/event"
	issue "github.com/kubecano/cano-collector/pkg/core/issue"
)

// MockWorkflowEngineInterface is a mock of WorkflowEngineInterface interface.
type MockWorkflowEngineInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowEngineInterfaceMockRecorder
}

// MockWorkflowEngineInterfaceMockRecorder is the mock recorder for MockWorkflowEngineInterface.
type MockWorkflowEngineInterfaceMockRecorder struct {
	mock *MockWorkflowEngineInterface
}

// NewMockWorkflowEngineInterface creates a new mock instance.
func NewMockWorkflowEngineInterface(ctrl *gomock.Controller) *MockWorkflowEngineInterface {
	mock := &MockWorkflowEngineInterface{ctrl: ctrl}
	mock.recorder = &MockWorkflowEngineInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowEngineInterface) EXPECT() *MockWorkflowEngineInterfaceMockRecorder {
	return m.recorder
}

// ExecuteWorkflowWithEnrichments mocks base method.
func (m *MockWorkflowEngineInterface) ExecuteWorkflowWithEnrichments(ctx context.Context, workflow *workflow.WorkflowDefinition, event event.WorkflowEvent) ([]issue.Enrichment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteWorkflowWithEnrichments", ctx, workflow, event)
	ret0, _ := ret[0].([]issue.Enrichment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteWorkflowWithEnrichments indicates an expected call of ExecuteWorkflowWithEnrichments.
func (mr *MockWorkflowEngineInterfaceMockRecorder) ExecuteWorkflowWithEnrichments(ctx, workflow, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteWorkflowWithEnrichments", reflect.TypeOf((*MockWorkflowEngineInterface)(nil).ExecuteWorkflowWithEnrichments), ctx, workflow, event)
}

// ExecuteWorkflowsWithEnrichments mocks base method.
func (m *MockWorkflowEngineInterface) ExecuteWorkflowsWithEnrichments(ctx context.Context, workflows []*workflow.WorkflowDefinition, event event.WorkflowEvent) ([]issue.Enrichment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteWorkflowsWithEnrichments", ctx, workflows, event)
	ret0, _ := ret[0].([]issue.Enrichment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteWorkflowsWithEnrichments indicates an expected call of ExecuteWorkflowsWithEnrichments.
func (mr *MockWorkflowEngineInterfaceMockRecorder) ExecuteWorkflowsWithEnrichments(ctx, workflows, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteWorkflowsWithEnrichments", reflect.TypeOf((*MockWorkflowEngineInterface)(nil).ExecuteWorkflowsWithEnrichments), ctx, workflows, event)
}

// SelectWorkflows mocks base method.
func (m *MockWorkflowEngineInterface) SelectWorkflows(event event.WorkflowEvent) []*workflow.WorkflowDefinition {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectWorkflows", event)
	ret0, _ := ret[0].([]*workflow.WorkflowDefinition)
	return ret0
}

// SelectWorkflows indicates an expected call of SelectWorkflows.
func (mr *MockWorkflowEngineInterfaceMockRecorder) SelectWorkflows(event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectWorkflows", reflect.TypeOf((*MockWorkflowEngineInterface)(nil).SelectWorkflows), event)
}
