apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cano-collector.fullname" . }}-workflows-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cano-collector.name" . }}
    chart: {{ include "cano-collector.chart" . }}
type: Opaque
stringData:
  workflows.yaml: |
    active_workflows:
    {{- range .Values.workflows.active_workflows }}
      - name: "{{ .name }}"
        triggers:
        {{- range .triggers }}
          - on_alertmanager_alert:
            {{- if .on_alertmanager_alert.alert_name }}
              alert_name: "{{ .on_alertmanager_alert.alert_name }}"
            {{- end }}
            {{- if .on_alertmanager_alert.status }}
              status: "{{ .on_alertmanager_alert.status }}"
            {{- end }}
            {{- if .on_alertmanager_alert.severity }}
              severity: "{{ .on_alertmanager_alert.severity }}"
            {{- end }}
            {{- if .on_alertmanager_alert.namespace }}
              namespace: "{{ .on_alertmanager_alert.namespace }}"
            {{- end }}
            {{- if .on_alertmanager_alert.instance }}
              instance: "{{ .on_alertmanager_alert.instance }}"
            {{- end }}
            {{- if .on_alertmanager_alert.pod_name }}
              pod_name: "{{ .on_alertmanager_alert.pod_name }}"
            {{- end }}
        {{- end }}
        actions:
        {{- range .actions }}
          - action_type: "{{ .action_type }}"
            data:
            {{- range $key, $value := .data }}
              {{- if kindIs "string" $value }}
              {{ $key }}: "{{ $value }}"
              {{- else if kindIs "bool" $value }}
              {{ $key }}: {{ $value }}
              {{- else if kindIs "int" $value }}
              {{ $key }}: {{ $value }}
              {{- else }}
              {{ $key }}: {{ $value | toYaml | nindent 16 }}
              {{- end }}
            {{- end }}
        {{- end }}
        {{- if .stop }}
        stop: {{ .stop }}
        {{- end }}
    {{- end }} 