apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cano-collector.fullname" . }}-teams
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cano-collector.name" . }}
    chart: {{ include "cano-collector.chart" . }}
data:
  teams.yaml: |
    teams:
      {{- range .Values.teams }}
      - name: "{{ .name }}"
        destinations: {{ toJson .destinations }}
      {{- end }}
