apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cano-collector.fullname" . }}-destination-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cano-collector.name" . }}
    chart: {{ include "cano-collector.chart" . }}
type: Opaque
stringData:
  destinations.yaml: |
    destinations:
      slack:
      {{- range .Values.destinations.slack }}
        {{- include "cano-collector.validateSlackDestination" . | nindent 8 }}
        - name: "{{ .name }}"
        {{- if .api_key }}
          api_key: "{{ .api_key }}"
        {{- else if .api_key_value_from }}
          api_key: "${SLACK_API_KEY_{{ .name | upper | replace "-" "_" }}}"
        {{- end }}
        {{- if .slack_channel }}
          slack_channel: "{{ .slack_channel }}"
        {{- end }}
        {{- if .grouping_interval }}
          grouping_interval: {{ .grouping_interval }}
        {{- end }}
        {{- if .unfurl_links }}
          unfurl_links: {{ .unfurl_links }}
        {{- end }}
      {{- end }}
