apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cano-collector.fullname" . }}-destination-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cano-collector.name" . }}
    chart: {{ include "cano-collector.chart" . }}
type: Opaque
stringData:
  destinations.yaml: |
    destinations:
      slack:
      {{- range .Values.destinations.slack }}
        - name: "{{ .name }}"
          webhookURL: "{{ .webhookURL }}"
      {{- end }}
      teams:
      {{- range .Values.destinations.msteams }}
        - name: "{{ .name }}"
          webhookURL: "{{ .webhookURL }}"
      {{- end }}
