{{ if .Values.collector.sentry_dsn }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cano-collector.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SENTRY_DSN: {{ .Values.collector.sentry_dsn | quote }}
{{ end }}
