apiVersion: v1
kind: Service
metadata:
  name: {{ include "cano-collector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cano-collector.labels" . | nindent 4 }}
{{- if .Values.collector.service.annotations }}
  annotations:
{{ toYaml .Values.collector.service.annotations | indent 4 }}
{{- end }}
spec:
  selector:
    {{- include "cano-collector.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
